#!/bin/bash

this_path=$(dirname $0)
release_path=$this_path/Release
hex_file=$(ls $release_path/*.hex)
echo $hex_file
echo $0 myargs $*




scp $hex_file aquapi@aquapi600.lan:~/ 
#ssh aquapi@aquapi600.lan "kill \$(pgrep screen)"
ssh aquapi@aquapi600.lan "sudo avrdude -p atmega328p  -V -c pi_1 -U flash:w:$(basename $hex_file):i"
